/**
 * Regenerates src/core/models.generated.ts and the Printer Model dropdown in package.json
 * from the printer database inside @point-of-sale/receipt-printer-encoder, which the
 * package uses internally but does not export.
 *
 * Run after upgrading the encoder: npm run gen-models
 */
import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import path from "node:path";
import vm from "node:vm";
import * as prettier from "prettier";

const root = path.resolve(import.meta.dirname, "..");
const require = createRequire(import.meta.url);
const source = readFileSync(require.resolve("@point-of-sale/receipt-printer-encoder"), "utf8");

const start = source.indexOf("const codepageMappings = {");
const end = source.indexOf("class ReceiptPrinterEncoder {");
if (start < 0 || end < 0) throw new Error("Printer tables not found: the encoder's source layout changed.");

type Definition = {
  vendor: string;
  model: string;
  media?: { dpi?: number; width?: number };
  capabilities: {
    language: "esc-pos" | "star-prnt" | "star-line";
    codepages: string;
    fonts: Record<string, { size: string; columns: number }>;
    cutter?: { feed?: number };
  };
};

const context: { codepageMappings?: Record<string, Record<string, (string | undefined)[]>>; printerDefinitions?: Record<string, Definition> } = {};
vm.runInNewContext(
  `${source.slice(start, end)}\nthis.codepageMappings = codepageMappings; this.printerDefinitions = printerDefinitions;`,
  context,
);
const mappings = context.codepageMappings!;
const definitions = context.printerDefinitions!;

// Bluetooth "cat" printers only take images over BLE, so they can't be used over the network.
const EXCLUDED = new Set(["meow"]);

const codepageSets: Record<string, string[]> = {};
const models: Record<string, object> = {};

for (const [id, def] of Object.entries(definitions)) {
  if (EXCLUDED.has(id)) continue;
  const caps = def.capabilities;
  const setKey = `${caps.language}:${caps.codepages}`;
  codepageSets[setKey] ??= [...new Set(mappings[caps.language][caps.codepages].filter((c): c is string => !!c))];
  models[id] = {
    name: `${def.vendor} ${def.model}`.trim(),
    vendor: def.vendor,
    model: def.model,
    dpi: def.media?.dpi ?? 203,
    paperMm: def.media?.width ?? 80,
    language: caps.language,
    codepageMapping: caps.codepages,
    codepageSet: setKey,
    columns: caps.fonts.A.columns,
    fontBColumns: caps.fonts.B?.columns ?? null,
    cutFeed: caps.cutter?.feed ?? 4,
  };
}

const generated = `// Generated by scripts/gen-models.ts from @point-of-sale/receipt-printer-encoder. Do not edit.

export const CODEPAGE_SETS = ${JSON.stringify(codepageSets, null, 2)} as const;

export const MODELS = ${JSON.stringify(models, null, 2)} as const;
`;
const generatedPath = path.join(root, "src/core/models.generated.ts");
prettier
  .resolveConfig(generatedPath)
  .then((config) => prettier.format(generated, { ...config, filepath: generatedPath }))
  .then((formatted) => writeFileSync(generatedPath, formatted));

// Keep the preferences dropdown in sync.
const manifestPath = path.join(root, "package.json");
const manifest = JSON.parse(readFileSync(manifestPath, "utf8"));
const pref = manifest.preferences.find((p: { name: string }) => p.name === "printerModel");
const GENERIC: Record<string, string> = { "pos-5890": "POS-5890 (generic 58 mm)", "pos-8360": "POS-8360 (generic 80 mm)" };
pref.data = [
  { title: "Auto-detect", value: "auto" },
  ...Object.entries(models).map(([id, m]) => ({ title: GENERIC[id] ?? (m as { name: string }).name, value: id })),
];
writeFileSync(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`);

console.log(`Wrote ${Object.keys(models).length} models and ${Object.keys(codepageSets).length} code page sets.`);
